language: "zh"
pipeline:
  - name: "tokenizer_jieba"
  - name: "intent_featurizer_wordvector"
    vector: "./data/word2vec.model"
  - name: "intent_classifier_tensorflow_embedding_bert"
    epochs: 200
  - name: "ner_crf"
  - name: "ner_synonyms"